# Site settings
title: Peek Possibilities, LLC | OT
description: "Helping moms heal and kids thrive."
baseurl: "" # the subpath of your site, e.g. /blog
url: "brittleigh.github.io/peekpossibilities/" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Peek Possibilities, LLC
    hero_description: Helping moms heal and kids thrive.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 575-208-5434
    email: peekpossibilities@gmail.com
    address: Roswell, NM

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2019 Peek Possibilities, LLC - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
