# Site settings
title: McCall Consulting, LLC | Tech & VA
description: "A one-stop shop for all of your technology and VA needs."
baseurl: /mccallconsulting # the subpath of your site, e.g. /blog
url: brittleigh.github.io # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: McCall Consulting, LLC
    hero_description: A one-stop shop for all of your technology and VA needs.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 515 999 0221
    email: joshmccall221@gmail.com
    address: Remote Work- based in PNW

# Opening hours
    monday_friday: 9:00 – 15:00
    saturday: 8:00 – 12:00
    sunday: By appt online

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Redmond, WA
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2017 McCall Consulting, LLC - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
